services:
  - type: web
    name: speechstar-web
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
    healthCheckPath: /health